<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["/", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<div class="page-header">
    <h1>
        Sign up
    </h1>
</div>
<?php echo $this->getContent() ?>
<?php echo $this->tag->form(
    [
        "signup/register",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
); ?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "name"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "email"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Register", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>