<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search students
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["students/new", "Create students"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "students/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<!--<div class="form-group">-->
<!--    <label for="fieldStudentid" class="col-sm-2 control-label">StudentID</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["StudentID", "type" => "number", "class" => "form-control", "id" => "fieldStudentid"]) ?>
<!--    </div>-->
<!--</div>-->

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">LastName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["LastName", "size" => 30, "class" => "form-control", "id" => "fieldLastname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">FirstName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["FirstName", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCity" class="col-sm-2 control-label">City</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["City", "size" => 30, "class" => "form-control", "id" => "fieldCity"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
