<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php
                echo $this->tag->linkTo(
                    "signup",
                    "Sign Up Here!"
                );
                ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["login", "login "]); ?></li>
        </ul>
    </nav>
</div>
<div class="page-header">
    <h1>WellCome</h1>
</div>


<p>This is a phalcon testing Project</p>

<p>This Is a School Management System</p>
<?php echo $this->getContent() ?>

